---
title: "integration"
author: "heinin"
date: "2024-10-24"
output:
  workflowr::wflow_html:
    code_folding: hide
  html_notebook: default
editor_options:
  chunk_output_type: console
---

## Processing 10x data

### Libraries and environment variables

```{r, message = F, warning = F}

library(workflowr)
library(Seurat)
library(googlesheets4)
library(tidyverse)
library(plyr)

setwd("/home/hnatri/19130_CAR_production/")
set.seed(1234)
options(future.globals.maxSize = 30000 * 1024^2)
reduction <- "integratedSCTumap"

source("/home/hnatri/SingleCellBestPractices/scripts/preprocessing_qc_module.R")
source("/home/hnatri/SingleCellBestPractices/scripts/integration_module.R")
source("/home/hnatri/19130_CAR_production/code/colors_themes.R")

```

### Import data

```{r, message = F, warning = F, eval = F}

# Metadata
# https://docs.google.com/spreadsheets/d/1DstdK4vXjk7ZEeBalW_4CA6Vmd57BGENUx3iMDRLszk/edit?usp=sharing
gs4_deauth()
production_samples  <- gs4_get("https://docs.google.com/spreadsheets/d/1DstdK4vXjk7ZEeBalW_4CA6Vmd57BGENUx3iMDRLszk/edit?usp=sharing")
#sheet_names(production_samples)
production_metadata <- read_sheet(production_samples, sheet = "Samples solo")

# Seurat list
seurat_list <- readRDS("/scratch/hnatri/CART/19130_CARprod_seurat_list_filtered.rds")

# Running SCTransform
seurat_list <- run_sctransform(seurat_list = seurat_list,
                               n_variable_features = 1000,
                               vars_to_regress = c("percent.mt_RNA",
                                                   "percent.ribo_RNA",
                                                   "S.Score",
                                                   "G2M.Score"))

```

### Integrate

```{r, message = F, warning = F, eval = F}

data[1:10, 1:10]

# Integration
integrated_seurat <- sct_rpca_integration(seurat_list = seurat_list)

integrated_seurat$Sample_Name <- paste0(integrated_seurat$Sample_Type, "_",
                                        integrated_seurat$Day)

integrated_seurat$Sample_Type <- factor(integrated_seurat$Sample_Type,
                                        levels = c("Mock", "Pre_CAR",
                                                   "5050_CAR", "CAR"))
integrated_seurat$Day <- factor(integrated_seurat$Day,
                                levels = c(0, 1, 4, 7, 14))

integrated_seurat$Day_chr <- factor(as.character(integrated_seurat$Day),
                                levels = c("0", "1", "4", "7", "14"))

#saveRDS(integrated_seurat, "/scratch/hnatri/CART/19130_CAR_production_integrated.rds")
# Moved to lab storage: /tgen_labs/banovich/pediatric_CAR-T/02_production

```

### Plotting

```{r, message = F, warning = F, fig.width = 12, fig.height = 4}

integrated_seurat <- readRDS("/tgen_labs/banovich/pediatric_CAR-T/02_production/19130_CAR_production_integrated.rds")

p1 <- DimPlot(integrated_seurat,
        group.by = "integratedSCTsnn_res.0.3",
        reduction = reduction,
        label = T,
        label.box = T,
        label.size = 3,
        repel = T,
        raster = T,
        raster.dpi = c(1024, 1024),
        pt.size = 3) +
  ggtitle("integratedSCTsnn_res.0.3") +
  theme_classic() +
  NoLegend() +
  NoAxes() +
  coord_fixed(1)

p2 <- DimPlot(integrated_seurat,
        group.by = "integratedSCTsnn_res.0.5",
        reduction = reduction,
        label = T,
        label.box = T,
        label.size = 3,
        repel = T,
        raster = T,
        raster.dpi = c(1024, 1024),
        pt.size = 3) +
  ggtitle("integratedSCTsnn_res.0.5") +
  theme_classic() +
  NoLegend() +
  NoAxes() +
  coord_fixed(1)

p3 <- DimPlot(integrated_seurat,
        group.by = "integratedSCTsnn_res.0.8",
        reduction = reduction,
        label = T,
        label.box = T,
        label.size = 3,
        repel = T,
        raster = T,
        raster.dpi = c(1024, 1024),
        pt.size = 3) +
  ggtitle("integratedSCTsnn_res.0.8") +
  theme_classic() +
  NoLegend() +
  NoAxes() +
  coord_fixed(1)

p1 + p2 + p3

integrated_seurat$cluster <- integrated_seurat$integratedSCTsnn_res.0.3

p4 <- DimPlot(integrated_seurat,
        group.by = "cluster",
        cols = product_cluster_col,
        reduction = reduction,
        label = T,
        label.box = T,
        label.size = 3,
        repel = T,
        raster = T,
        raster.dpi = c(1024, 1024),
        pt.size = 3) +
  ggtitle("") +
  theme_classic() +
  NoLegend() +
  NoAxes() +
  coord_fixed(1)

p5 <- DimPlot(integrated_seurat,
        group.by = "Sample_Type",
        cols = sample_type_col,
        reduction = reduction,
        raster = T,
        raster.dpi = c(1024, 1024),
        pt.size = 3) +
  ggtitle("") +
  theme_classic() +
  NoAxes() +
  coord_fixed(1)

p6 <- DimPlot(integrated_seurat,
        group.by = "Day_chr",
        cols = day_col,
        reduction = reduction,
        raster = T,
        raster.dpi = c(1024, 1024),
        pt.size = 3) +
  ggtitle("") +
  theme_classic() +
  NoAxes() +
  coord_fixed(1)

p4 + p5 + p6

p7 <- DimPlot(integrated_seurat,
              group.by = "cluster",
              split.by = "Sample_Type",
              cols = product_cluster_col,
              reduction = reduction,
              raster = T,
              raster.dpi = c(1024, 1024),
              pt.size = 3) +
        ggtitle("") +
        theme_classic() +
        NoLegend() +
        NoAxes() +
        coord_fixed(1)

p8 <- DimPlot(integrated_seurat,
              group.by = "cluster",
              split.by = "Day",
              cols = product_cluster_col,
              reduction = reduction,
              raster = T,
              raster.dpi = c(1024, 1024),
              pt.size = 3) +
        ggtitle("") +
        theme_classic() +
        NoLegend() +
        NoAxes() +
        coord_fixed(1)

p7

p8

```

